octokit/fixtures

README.md

README: updated record scenario instructions

---

bin/record.js
lib/record-scenario.js
lib/remove-credentials.js

rebased on #30, merge that first, then rebase on `master`

refactor: simplify lib/record-scenario.js

---

CODE_OF_CONDUCT.md

Contributor Covenant

---

scenarios/api.github.com/get-content/normalized-fixture.json
scenarios/api.github.com/get-content/raw-fixture.json
scenarios/api.github.com/get-content/record.js
scenarios/api.github.com/get-content/test.js

scenario: get content

---

lib/normalize/combined-status.js
lib/normalize/content.js
lib/normalize/status.js
scenarios/api.github.com/create-status/normalized-fixture.json
scenarios/api.github.com/create-status/test.js

fixturize sha hashes in create-file scenario

---

package.json

remove follow-redirects workaround

---

.gitignore
package.json

upload binaries to releases

---

lib/normalize/index.js

ignore all now.sh headers (from proxy)

---

README.md

Fix fixtures link
Maybe wrong ?
-----
[View rendered README.md](https://github.com/williamdes/fixtures/blob/patch-1/README.md)

Fix fixtures link

---

package.json

chore(package): update into-stream to version 5.1.0

---

package.json

chore(package): update get-stream to version 5.1.0

---

.gitignore
package-lock.json
package.json

chore(package): update tap to version 13.0.3

---

package-lock.json
package.json

Greenkeeper/axios debug log 0.6.1

---

bin/record.js
package-lock.json
package.json
scenarios/api.github.com/add-and-remove-repository-collaborator/test.js
scenarios/api.github.com/add-labels-to-issue/test.js
scenarios/api.github.com/create-file/test.js
scenarios/api.github.com/create-status/test.js
scenarios/api.github.com/errors/test.js
scenarios/api.github.com/get-archive/test.js
scenarios/api.github.com/get-content/test.js
scenarios/api.github.com/get-organization/test.js
scenarios/api.github.com/get-repository/test.js
scenarios/api.github.com/get-root/test.js
scenarios/api.github.com/git-refs/test.js
scenarios/api.github.com/markdown/test.js
scenarios/api.github.com/project-cards/test.js
scenarios/api.github.com/release-assets-conflict/test.js
scenarios/api.github.com/release-assets/test.js
scenarios/api.github.com/search-issues/test.js
test/integration/additions-test.js
test/integration/smoke-test.js

Greenkeeper/standard 14.0.2

---

lib/write.js
package-lock.json
package.json

fixes #281, requires code changes

Greenkeeper/mkdirp 1.0.3

---

README.md

-----
[View rendered README.md](https://github.com/dominguezcelada/fixtures/blob/patch-1/README.md)

Fix type on README.md

---

bin/record.js

This was a potential source of the problem, but didn't fix it.
It refactors `bin/record.js` to use async funtions with `async`/`await` and a for-of-loop instead of `Array#reduce()` with `Promise.resolve()`.
This improves the readability of the code and helps with the understanding of the flow

refactor(bin/record): use for-of-loop and async functions instead of `Array#reduce()` with `Promise.resolve()`

---

.github/pull_request_template.md
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml

This changes the default branch from master --> main across the repository content to match the state of the repository settings. 
----
* Links, Actions, and references used the "master" default branch name. 
* Links, Actions, and references use the "main" default branch name
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!
If `Yes`, what's the impact:  
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----

Default branch rename

---

package.json

Follows up on #534 but adds the release block I didn't catch until Gregor did on [fixtures-server here](https://github.com/octokit/fixtures-server/pull/260). 
----
* Releases to NPM were blocked due to missing configuration for the new default branch. 
*Releases to NPM are unblocked. 
* N/A
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----

Add release block to package.json

---

.github/workflows/codeql-analysis.yml

Part of ensuring that each repo of ours has a build and a CodeQL step. 
----
* The CodeQL workflow was disabled because CodeQL was failing (see [here](https://github.com/octokit/fixtures/actions/runs/3526444943) for an example). 
* The CodeQL workflow is enabled and CodeQL is passing.
* N/A
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----

Fix CodeQL Action
